title: Adventure Code
description: Exploring coding, machine learning and other interesing topics
show_downloads: true
theme: jekyll-theme-minimal
markdown: CommonMarkGhPages # Needed for collapsable markdown
