title: Adventure Code
description: Exploring coding, machine learning and other interesing topics
logo: ./bmo.jpg
theme: jekyll-theme-minimal
markdown: CommonMarkGhPages # Needed for collapsable markdown
